### ISSUE TITLE
Feature Request: Ability to Toggle Sticky Mode Without Opening Stickiness Menu

### ISSUE THREAD

**Issue by the-phuctran** [hereafter/stickywindows#10]
I know it's not take much time if I use the menu after Windowskey + rightclick or Win + F10 but as a GestureSign app user this is the most expected feature to me to perform a quick pin with only a fast draw of right mouse button. As I mean can the app have a shortcut key to do both Sticky and Unsticky to a window directly?

**Comment by hereafter** [comment]
Good idea, i will now start work on this feature

**Comment by hereafter** [comment]
see #13

**Comment by hereafter** [comment]
@the-phuctran hi, a new release 2.1 is out there in Microsoft Store. Please kindly try out and see if those enhancements helps. Thanks
