### ISSUE TITLE
app wont work on win 10 v1903

### ISSUE THREAD

**Issue by SONNYHURTADO** [hereafter/stickywindows#2]
hi, sadly the app Sticky Windows stopped working after windows 10 update to version 1903, on the app list dont appear the Sticky Notes app, like use to,  please help me to solve this problem. Thanks
![image](https://user-images.githubusercontent.com/51746817/59348797-ae36d180-8cdd-11e9-99ab-d78a9a4491b4.png)

**Comment by hereafter** [comment]
thanks for reporting, I am able to reproduce the issue, expect a fix soon

**Comment by hereafter** [comment]
further inspection suggest StickyNotes team made some breaking (to sticky windows) changes, so sticky windows filtered it out. a fix is posted in windows store. I'll update here once it is released

**Comment by hereafter** [comment]
it is live now, please get the fix from app store @SONNYHURTADO

**Comment by SONNYHURTADO** [comment]
solved, thanks!!
