### ISSUE TITLE
Chrome window doesn't get sticky if enabled while it is minimized

### ISSUE THREAD

**Issue by destrofer** [hereafter/stickywindows#3]
Title says it all. I tried notepad++ and it seems to have no such issue. Disabling chrome window sticky state while minimized works too.

Some information, if it helps:
OS: Windows 10
Chrome: 75.0.3770.100

**Comment by hereafter** [comment]
yes, it is annoying, I will see what I can do.

If possible, could you try to use "Win+Right mouse" to change, that way it sure is a visible window.

anyway, thanks a lot for reporting this issue.

**Comment by hereafter** [comment]
no repro with newer versions

Version 89.0.4389.82 (Official Build) (64-bit)
