### ISSUE TITLE
Stickiness doesn't work for Excel.exe

### ISSUE THREAD

**Issue by fredskis** [hereafter/stickywindows#4]
Trying through Sticky Windows app toggle as well as directly through context menu. Doesn't work :( 

Currently running version 16.0.12105.20000 - Excel for Office 365

Same with Windows Store (WinStore.App.exe)

**Comment by hereafter** [comment]
yes, apparently the mouse picks a wrong window.  investing this issue further for a fix.
however, the application lists all the books correctly, and use the list toggles the "stickiness" of a target book correctly. 

Could you please use the "Sticky Windows" main list to toggle as a workaround first?

**Comment by hereafter** [comment]
as 
![image](https://user-images.githubusercontent.com/1483954/115694233-40f12e80-a393-11eb-9cba-cfaf01fe2a88.png)

this issue is fixed by Microsoft?
