### ISSUE TITLE
Feature Request: Update List of Windows Automatically

### ISSUE THREAD

**Issue by jcg3675** [hereafter/stickywindows#7]
Upon reactivating the window (after switching away to a different app) the list of apps should auto update to show windows that may have been opened since I was last using the app.

**Comment by hereafter** [comment]
noted thanks

**Comment by hereafter** [comment]
- [x] "Refresh" whenever a new window is activated
- [x]  Reduce flickering when list refreshed

**Comment by hereafter** [comment]
See Release 2.1 Progress
