### ISSUE TITLE
Issues with Microsoft Teams

### ISSUE THREAD

**Issue by XStreines** [hereafter/stickywindows#8]
Sometimes I am not able to stick some windows. I am having a lot of issues with Microsoft Teams, but in many cases when I click the option Sticky, nothing happens.

**Comment by cognition** [comment]
+1
I get the same issue, with both the meta+right click and the app window, the switch toggles as soon as something covers it. 
Is there a way of pulling debug logs to assist in troubleshooting the issue?

**Comment by hereafter** [comment]
i tried teams, the app is ok with it.

What is your OS version, and are there any steps to reproduce the issue?


@

**Comment by cognition** [comment]
It's working now!
*Ramon Brooker*

rbrooker@aeo3.ca

**Comment by XStreines** [comment]
It seems to be working fine now but I would like to have the Teams notifications also stick over other apps, how can I do that?

**Comment by hereafter** [comment]
let me investigate the issue further.
