### ISSUE TITLE
Feature Request: System Notification Icon Changes Based On Current Window Status

### ISSUE THREAD

**Issue by the-phuctran** [hereafter/stickywindows#9]
As my idea, when we click in a window, the icon on notification area will change its shape to pin/unpin icon or recolor to a different color (e.g red/grey) based on its "sticky status", just a quick way to indicate their toggle instead of looking in the update list.

**Comment by hereafter** [comment]
Thanks for the suggestion i will now start working on this feature

**Comment by hereafter** [comment]
see #11
